workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/ || $CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

stages:
  - doc
  - release

include:
  - local: '.gitlab/workflows/release.yml'
  - local: '.gitlab/workflows/terraform-doc.yml'
