stages:
  - doc
  - release

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      when: always

include:
  - local: '.gitlab/workflows/release.yml'
  - local: '.gitlab/workflows/terraform-doc.yml'

generate-terraform-doc:
  extends:
    - .create-terraform-doc
    - .upload-terraform-doc
  rules:
    - changes:
        - 'modules/ecs-asg-cluster/**/*.tf'
      when: always
