stages:
  - doc
  - release

include:
  - local: '.gitlab/workflows/release.yml'
    rules:
      - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
        when: always

  - local: '.gitlab/workflows/terraform-doc.yml'
    rules:
      - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
        when: always

generate-terraform-doc:
  extends:
    - .create-terraform-doc
    - .upload-terraform-doc
  rules:
    - changes:
        - 'modules/ecs-asg-cluster/**/*.tf'
      when: always
