default:
  tags:
    - infra-core-docker

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
      when: always
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - 'modules/ecs-asg-cluster/**/*.tf'
        - '.gitlab/workflows/terraform-docs.yml'
      when: always

include:
  - local: '.gitlab/workflows/release.yml'
  - local: '.gitlab/workflows/terraform-docs.yml'
