stages:
  - doc
  - release

include:
  - local: '.gitlab/workflows/release.yml'
    rules:
      - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
        when: always

  - local: '.gitlab/workflows/terraform-doc.yml'
    rules:
      - if: 'CI_PIPELINE_SOURCE == "merge_request_event"'
        # changes: # TODO: Add in Next Release
        #   - 'modules/ecs-asg-cluster/**/*.tf'
        when: always
