workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/ || $CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"'
      when: always
    - when: never

stages:
  - doc
  - release

include:
  - local: '.gitlab/workflows/release.yml'
    rules:
      - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
        when: always
      - when: never

  - local: '.gitlab/workflows/terraform-doc.yml'
    rules:
      - if: '$CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"'
        when: always
      - when: never
