stages:
  - doc
  - release

include:
  - local: '.gitlab/workflows/release.yml'
    rules:
      - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
        when: always

  - local: '.gitlab/workflows/terraform-doc.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
        when: always

manual-doc:
  stage: doc
  trigger:
    include: '.gitlab/workflows/terraform-doc.yml'
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
