workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
      when: always
    - when: never

stages:
  - doc
  - release

changelog:
  image:
    name: orhunp/git-cliff:latest
    entrypoint: ['']
  variables:
    GIT_STRATEGY: clone # clone entire repo instead of reusing workspace
    GIT_DEPTH: 0 # avoid shallow clone to give cliff all the info it needs
  stage: doc
  script:
    - git-cliff --latest -r . > release_notes.md
    - git-cliff -r . > CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md
      - release_notes.md

upload_changelog:
  stage: release
  image: alpine:latest
  needs:
    - job: changelog
      artifacts: true
  script:
    - apk add curl jq
    - >
      CONTENT=$(cat CHANGELOG.md | base64 -w 0) &&
      curl --request PUT --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN"
      --header "Content-Type: application/json" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/files/CHANGELOG.md"
      --data "{\"branch\":\"$CI_DEFAULT_BRANCH\",\"encoding\":\"base64\",\"content\":\"$CONTENT\",\"commit_message\":\"Update CHANGELOG.md for version $CI_COMMIT_TAG\"}"

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: changelog
      artifacts: true
  script:
    - echo "Creating release"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: release_notes.md
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
